# Generated by Django 5.0.4 on 2024-05-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_custormer_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Customer',
            new_name='customer',
        ),
    ]
